name: Flet 应用构建

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 检出仓库
        uses: actions/checkout@v4

      - name: 2. 安装 ninja-build libgtk-3-dev
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev

      - name: 3. 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      
      - name: 4. 安装环境
        run: pip install -r requirements.txt

      - name: 5. 安装 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 6. 安装 Android SDK
        uses: android-actions/setup-android@v3

      - name: 7. 安装 Flutter SDK
        run: |
          FLUTTER_VERSION="3.24.5"
          FLUTTER_CHANNEL="stable"
          mkdir -p $HOME/flutter
          wget -q https://storage.googleapis.com/flutter_infra_release/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_${FLUTTER_VERSION}-${FLUTTER_CHANNEL}.tar.xz -O flutter.tar.xz
          tar -xf flutter.tar.xz -C $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          export PATH="$HOME/flutter/bin:$PATH"
          rm flutter.tar.xz
      
      - name: 8. 安装 Android Studio
        run: |
          wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.2.1.9/android-studio-2024.2.1.9-linux.tar.gz
          tar -zxvf android-studio-2024.2.1.9-linux.tar.gz
          sudo mv android-studio /opt/
          rm android-studio-2024.2.1.9-linux.tar.gz

      - name: 9. 设置 Gradle 构建内存
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > ~/.gradle/gradle.properties

      - name: 10. 构建 App
        run: |
          flet build apk --split-per-abi
      
      - name: 11. 上传至 Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/apk